### ISSUE TITLE
Python 2.6

### ISSUE THREAD

**Issue by rienafairefr** [iot-lab/cli-tools#19]
I think the End of Life Python 2.6 has been officially dropped from support for py.test (https://github.com/pytest-dev/py/pull/165) so travis builds are failing.

We could probably require a py test dependency pegged at a previous version (maybe pytest 3.2), but is that worth it I don't know

**Comment by aabadie** [comment]
Indeed, and as I can see, the [build fails because of this](https://travis-ci.org/iot-lab/cli-tools).

I would be in favour of dropping the support for python 2.6. I already tried in the past but it was rejected because python 2.6 was still used in Rennes (still using Debian wheezy). Now that Rennes is stopped, I think it's safe to remove python 2.6.

What do you think ? @fsaintma ?

**Comment by fsaintma** [comment]
I agree with you, drop python2.6 support
