### ISSUE TITLE
Change CI infrastructure

### ISSUE THREAD

**Issue by aabadie** [iot-lab/cli-tools#8]
I open this issue to discuss about the switch to Travis CI.
The CLI Tools are now using ci.inria.fr and Jenkins for their CI infrastructure. But I see several limitations:
* It doesn't integrate nicely into github workflow
* We have access to a limited list of Python versions (and partially out-dated, python 3.6 ?)

Looking at what was achieved in the ssh-cli-tools : using Travis and Codecov, keeping tox and use pytest. I think we could work on that.

Opinions ?

**Comment by cladmi** [comment]
I will sum-up the live discussion.

Pytest discussion is in https://github.com/iot-lab/cli-tools/issues/7

As it is a pure IoT-LAB software I have rather like to to keep the tests on Inria integration system with the other software tests. This way, there is only one thing to maintain.
Also, tests can be run anywhere without requiring a travis setup with ``tox``.

The changes number on github is low enough and only done by admins, so DEV.md could be improved. If really needed, jenkins also supports github integration but it may not be worth the time adding it.

I like the idea of adding "Build passing" and "Coverage" bagdes from jenkins build but never did it.
There already is the 'build passing' badge plugin installed, but I did not find a directly available plugin for coverage. 

Regarding python versions, they should just be added to the build slave.
It could be a goal to remove the jenkins ``skip_missing_interpreters = True``line in tox.
Using ``pyenv`` would allow easily having several python versions.

However, currently it is still running a debian jessie, so I would like to see it upgraded before adding too many new things.

### As a side note

Really required versions are the one used on IoT-LAB servers: python2.6 and python2.7. The other maintained versions are here just because we are "nice to users who only want to use python3 on their computer" as they are not required for the testbed.

In the same way as firmware compilation is only expected to work on the frontend versions. Compiling/working under arm-gcc 5 or 6 is completely ignored because of lack of maintenance time available.

It does not mean it should be ignored, but it does not matter as much as the deployed versions.

**Comment by aabadie** [comment]
Even if adding Travis along with codecov for unittests is quite straight forward, I globally agree with the corporate idea of keeping the CI on the inria CI infrastructure.
It also make it simpler for integration tests were we require the use of account and password to run "real" test experiments.

+1 for adding the build passing from Jenkins.

Ok for keeping python 2.6, +1 for the reason you mention about installed versions on the IoT-Lab servers.

If we stick to Jenkins, adding the coverage badge and integration with GitHub (only for PRs) are really nice to have features as well IMHO . This way we ensure future contributions (if any) doesn't introduce issues but should also improve team work by sharing the knowledge between devs (this is a personal opinion).

**Comment by cladmi** [comment]
CI server migrated to debian Wheezy, cannot upgrade because of the open-embedded job.
All needed python versions are installed with `pyenv`.

And I could remove `skip_missing_interpreters`

https://github.com/iot-lab/cli-tools/commit/8672e2fad8238c7c155c3806e3ab4b2cc83e2fe1

**Comment by aabadie** [comment]
Is the setup procedure of the VM documented somewhere ?

**Comment by cladmi** [comment]
Of course, it was already documented (2 years ago) in admin repository: https://github.com/iot-lab/iot-lab-dev/blob/master/continuous_integration/INSTALL

Now I added a fabric file here:

https://github.com/iot-lab/iot-lab-dev/tree/continuous_integration/continuous_integration

Needs some final fixup to add docstrings and fix last issue with `ssh-keyscan`.

**Comment by aabadie** [comment]
Good to know, thanks :)

**Comment by aabadie** [comment]
Since #15 is merged, we can close this one.
